name: Tests
on: ["push", "pull_request"]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [18.x]
    
        steps:
        - name: Git checkout
          uses: actions/checkout@v3
    
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
    
        - name: Install dependencies
          run: yarn install
    
        - name: Run tests and report coverage
          env:
            COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          run: |
            yarn test:cov
            ls -la ./coverage

        - name: Sending coveralls report
          uses: coverallsapp/github-action@master
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
