name: Tests
on: ["push", "pull_request"]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [18.x, 20.x]
            include:
              - os: 18.x
                platform: 1
              - os: 20.x
                platform: 2
    
        steps:
        - name: Git checkout
          uses: actions/checkout@v3
    
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
    
        - name: Install dependencies
          run: yarn install
    
        - name: Run tests and report coverage
          env:
            COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          run: |
            yarn test:cov
            ls -la ./coverage

        - name: Coveralls Parallel
          uses: coverallsapp/github-action@v2
          with:
            flag-name: run-${{ matrix.platform}}
            parallel: true

    finish:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: "run-1,run-2"
